### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by scorpiopio** [jimmy201602/django-gateone#3]
I run the docker of django-gateone as you said,but the browes is return the 502 error.
I login to the container and curl the url and return the 502.
```
root@3edd20219c98:/opt/django-gateone# curl http://localhost
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

**Comment by jimmy201602** [comment]
Sorry to hear that. Would you show me the detail log that i can detect where the bug is.

**Comment by scorpiopio** [comment]
I gave up and try shellinabox...but thank you any way~~
